### ISSUE TITLE
Shared cache among composers leads to KeyError

### ISSUE THREAD

**Issue by alexmojaki** [BusinessOptics/fn_graph#5]
Reproducing script:

```python
from fn_graph import Composer

c = Composer().update(foo=lambda x: x * 2, bar=lambda: 9).cache()
assert c.bar() == 9
assert c.update_parameters(x=2).foo() == 4
c.bar()  # KeyError: 'x'
```

1. `c` is a composer with a function `foo` which depends on a parameter `x` that hasn't been specified yet, and a function `bar` which doesn't depend on anything. `bar` can thus be calculated.
2. Creating a new composer with a value for `x` allows us to calculate `foo`. In the process, `'x'` is inserted into the `hashes` dict of the `SimpleCache` which both composers share.
3. Trying to calculate `bar` now fails. In the process of checking the cache, it finds `x` in `.dag()` (because `foo` depends on it) and in `._cache.hashes`, but not in `._functions` or `._parameters`.

```
Traceback (most recent call last):
  File "/home/alex/.config/JetBrains/PyCharm2020.1/scratches/scratch_693.py", line 6, in <module>
    c.bar()
  File "/home/alex/.cache/pypoetry/virtualenvs/stanbic-trader-solutions-py3.7/lib/python3.7/site-packages/fn_graph/__init__.py", line 347, in <lambda>
    return lambda: self.calculate([name])[name]
  File "/home/alex/.cache/pypoetry/virtualenvs/stanbic-trader-solutions-py3.7/lib/python3.7/site-packages/fn_graph/__init__.py", line 286, in calculate
    self, outputs, perform_checks, intermediates, progress_callback
  File "/home/alex/.cache/pypoetry/virtualenvs/stanbic-trader-solutions-py3.7/lib/python3.7/site-packages/fn_graph/calculation.py", line 299, in calculate
    results, _ = calculate_collect_exceptions(*args, raise_immediately=True, **kwargs)
  File "/home/alex/.cache/pypoetry/virtualenvs/stanbic-trader-solutions-py3.7/lib/python3.7/site-packages/fn_graph/calculation.py", line 187, in calculate_collect_exceptions
    maintain_cache_consistency(composer)
  File "/home/alex/.cache/pypoetry/virtualenvs/stanbic-trader-solutions-py3.7/lib/python3.7/site-packages/fn_graph/calculation.py", line 66, in maintain_cache_consistency
    node for node in dag if not composer._cache.valid(composer, node)
  File "/home/alex/.cache/pypoetry/virtualenvs/stanbic-trader-solutions-py3.7/lib/python3.7/site-packages/fn_graph/calculation.py", line 66, in <setcomp>
    node for node in dag if not composer._cache.valid(composer, node)
  File "/home/alex/.cache/pypoetry/virtualenvs/stanbic-trader-solutions-py3.7/lib/python3.7/site-packages/fn_graph/caches.py", line 81, in valid
    matches = self._hash(composer, key) == self.hashes[key]
  File "/home/alex/.cache/pypoetry/virtualenvs/stanbic-trader-solutions-py3.7/lib/python3.7/site-packages/fn_graph/caches.py", line 76, in _hash
    return hash_fn(composer, key, use_id=not self.hash_parameters)
  File "/home/alex/.cache/pypoetry/virtualenvs/stanbic-trader-solutions-py3.7/lib/python3.7/site-packages/fn_graph/caches.py", line 22, in hash_fn
    else composer._functions[key]
KeyError: 'x'
```

**Comment by JHSaunders** [comment]
This error is fixed in 0.14.1
